#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : automaton
Version  : 1.15.0
Release  : 32
URL      : https://files.pythonhosted.org/packages/2f/d2/08a63202b66d811dd86046de9abeb555098a316a7e8304dfb9f171b4c635/automaton-1.15.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2f/d2/08a63202b66d811dd86046de9abeb555098a316a7e8304dfb9f171b4c635/automaton-1.15.0.tar.gz
Summary  : Friendly state machines for python.
Group    : Development/Tools
License  : Apache-2.0
Requires: automaton-python3
Requires: automaton-license
Requires: automaton-python
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : configparser
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Automaton
        =========

%package license
Summary: license components for the automaton package.
Group: Default

%description license
license components for the automaton package.


%package python
Summary: python components for the automaton package.
Group: Default
Requires: automaton-python3

%description python
python components for the automaton package.


%package python3
Summary: python3 components for the automaton package.
Group: Default
Requires: python3-core

%description python3
python3 components for the automaton package.


%prep
%setup -q -n automaton-1.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532361942
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/automaton
cp LICENSE %{buildroot}/usr/share/doc/automaton/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/automaton/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
